version: '2'
services:
  admin:
    build:
      context: ./
      dockerfile: admin.dockerfile
    working_dir: /home/node/app
    user: "node"
    environment:
      - NODE_ENV=development
    volumes:
      - ../admin:/home/node/app
    ports:
      - "4200:4200"
    entrypoint: ["npm", "start", "-p", "4200"]
  backend:
    build:
      context: ./
      dockerfile: backend.dockerfile
    working_dir: /usr/src/app
    volumes:
      - ../backend:/usr/src/app
    ports:
      - "8000:8000"
    entrypoint: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
  postgres:
    build:
      context: ./
      dockerfile: postgres.dockerfile
    environment:
      - "POSTGRES_PASSWORD=postgres"
  redis:
    image: redis
